//! Token enum and Display impl. See `docs/lexer/keywords.md`.

use crate::intern::Symbol;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Int(i64),
    Float(f64),
    Str(String),
    True,
    False,
    None,
    Ident(Symbol),
    Is,
    Neq,
    Equals,
    Unless,
    Until,
    Returns,
    And,
    Or,
    Not,
    If,
    Elif,
    Else,
    While,
    For,
    In,
    Loop,
    Break,
    Continue,
    Return,
    Match,
    When,
    Type,
    Enum,
    Err,
    Pub,
    Use,
    As,
    From,
    To,
    By,
    Array,
    Asm,
    Extern,
    Do,
    End,
    Log,
    Of,
    Test,
    Embed,
    Assert,
    Query,
    Store,
    Migration,
    Insert,
    Delete,
    Set,
    Transaction,
    View,
    Actor,
    Spawn,
    Send,
    Receive,
    Trait,
    Impl,
    Dispatch,
    Yield,
    Channel,
    Close,
    Select,
    Stop,
    Default,
    Sim,
    Supervisor,
    Atomic,
    Strict,
    Xor,
    Unreachable,
    Alias,
    Defer,
    Deque,
    Grad,
    Einsum,
    Build,
    Syscall,
    Global,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Pipe,
    Caret,
    Ampersand,
    At,
    AtKw,
    Tilde,
    Shl,
    Shr,
    Ushr,
    Lt,
    Gt,
    LtEq,
    GtEq,
    Question,
    Bang,
    BangBang,
    Dollar,
    DollarDollar,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Comma,
    Colon,
    StarStar,
    Dot,
    Newline,
    Indent,
    Dedent,
    Eof,
    InterpStart,
    InterpEnd,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    AmpEq,
    PipeEq,
    CaretEq,
    ShlEq,
    ShrEq,
    UshrEq,
    CharLit(i64),
    DotDotDot,
}

impl std::fmt::Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Int(n) => write!(f, "{n}"),
            Self::Float(n) => write!(f, "{n}"),
            Self::Str(s) => write!(f, "'{s}'"),
            Self::True => f.write_str("true"),
            Self::False => f.write_str("false"),
            Self::None => f.write_str("none"),
            Self::Ident(s) => write!(f, "{s}"),
            Self::Is => f.write_str("is"),
            Self::Neq => f.write_str("neq"),
            Self::Equals => f.write_str("equals"),
            Self::Unless => f.write_str("unless"),
            Self::Until => f.write_str("until"),
            Self::Returns => f.write_str("returns"),
            Self::And => f.write_str("and"),
            Self::Or => f.write_str("or"),
            Self::Not => f.write_str("not"),
            Self::If => f.write_str("if"),
            Self::Elif => f.write_str("elif"),
            Self::Else => f.write_str("else"),
            Self::While => f.write_str("while"),
            Self::For => f.write_str("for"),
            Self::In => f.write_str("in"),
            Self::Loop => f.write_str("loop"),
            Self::Break => f.write_str("break"),
            Self::Continue => f.write_str("continue"),
            Self::Return => f.write_str("return"),
            Self::Match => f.write_str("match"),
            Self::When => f.write_str("when"),
            Self::Type => f.write_str("type"),
            Self::Enum => f.write_str("enum"),
            Self::Err => f.write_str("err"),
            Self::Pub => f.write_str("pub"),
            Self::Use => f.write_str("use"),
            Self::As => f.write_str("as"),
            Self::From => f.write_str("from"),
            Self::To => f.write_str("to"),
            Self::By => f.write_str("by"),
            Self::Array => f.write_str("array"),
            Self::Asm => f.write_str("asm"),
            Self::Extern => f.write_str("extern"),
            Self::Do => f.write_str("do"),
            Self::End => f.write_str("end"),
            Self::Log => f.write_str("log"),
            Self::Of => f.write_str("of"),
            Self::Test => f.write_str("test"),
            Self::Embed => f.write_str("embed"),
            Self::Assert => f.write_str("assert"),
            Self::Query => f.write_str("query"),
            Self::Store => f.write_str("store"),
            Self::Migration => f.write_str("migration"),
            Self::Insert => f.write_str("insert"),
            Self::Delete => f.write_str("delete"),
            Self::Transaction => f.write_str("transaction"),
            Self::View => f.write_str("view"),
            Self::Plus => f.write_str("+"),
            Self::Minus => f.write_str("-"),
            Self::Star => f.write_str("*"),
            Self::Slash => f.write_str("/"),
            Self::Percent => f.write_str("%"),
            Self::Pipe => f.write_str("|"),
            Self::Caret => f.write_str("^"),
            Self::Ampersand => f.write_str("&"),
            Self::At => f.write_str("@"),
            Self::AtKw => f.write_str("at"),
            Self::Tilde => f.write_str("~"),
            Self::Dollar => f.write_str("$"),
            Self::DollarDollar => f.write_str("$$"),
            Self::Shl => f.write_str("<<"),
            Self::Shr => f.write_str(">>"),
            Self::Ushr => f.write_str(">>>"),
            Self::Lt => f.write_str("<"),
            Self::Gt => f.write_str(">"),
            Self::LtEq => f.write_str("<="),
            Self::GtEq => f.write_str(">="),
            Self::Question => f.write_str("?"),
            Self::Bang => f.write_str("!"),
            Self::BangBang => f.write_str("!!"),
            Self::StarStar => f.write_str("pow"),
            Self::LParen => f.write_str("("),
            Self::RParen => f.write_str(")"),
            Self::LBracket => f.write_str("["),
            Self::RBracket => f.write_str("]"),
            Self::Comma => f.write_str(","),
            Self::Colon => f.write_str(":"),
            Self::Dot => f.write_str("."),
            Self::Newline => f.write_str("NEWLINE"),
            Self::Indent => f.write_str("INDENT"),
            Self::Dedent => f.write_str("DEDENT"),
            Self::Eof => f.write_str("EOF"),
            Self::InterpStart => f.write_str("INTERP_START"),
            Self::InterpEnd => f.write_str("INTERP_END"),
            Self::PlusEq => f.write_str("+="),
            Self::MinusEq => f.write_str("-="),
            Self::StarEq => f.write_str("*="),
            Self::SlashEq => f.write_str("/="),
            Self::AmpEq => f.write_str("&="),
            Self::PipeEq => f.write_str("|="),
            Self::CaretEq => f.write_str("^="),
            Self::ShlEq => f.write_str("<<="),
            Self::ShrEq => f.write_str(">>="),
            Self::UshrEq => f.write_str(">>>="),
            Self::CharLit(c) => write!(f, ":{}", char::from(*c as u8)),
            Self::DotDotDot => f.write_str("..."),
            Self::Actor => f.write_str("actor"),
            Self::Spawn => f.write_str("spawn"),
            Self::Send => f.write_str("send"),
            Self::Receive => f.write_str("receive"),
            Self::Trait => f.write_str("trait"),
            Self::Impl => f.write_str("impl"),
            Self::Dispatch => f.write_str("dispatch"),
            Self::Yield => f.write_str("yield"),
            Self::Set => f.write_str("set"),
            Self::Channel => f.write_str("channel"),
            Self::Close => f.write_str("close"),
            Self::Select => f.write_str("select"),
            Self::Stop => f.write_str("stop"),
            Self::Default => f.write_str("default"),
            Self::Sim => f.write_str("sim"),
            Self::Supervisor => f.write_str("supervisor"),
            Self::Atomic => f.write_str("atomic"),
            Self::Strict => f.write_str("strict"),
            Self::Xor => f.write_str("xor"),
            Self::Unreachable => f.write_str("unreachable"),
            Self::Alias => f.write_str("alias"),
            Self::Defer => f.write_str("defer"),
            Self::Deque => f.write_str("deque"),
            Self::Grad => f.write_str("grad"),
            Self::Einsum => f.write_str("einsum"),
            Self::Build => f.write_str("build"),
            Self::Syscall => f.write_str("syscall"),
            Self::Global => f.write_str("global"),
        }
    }
}
